### ISSUE TITLE
Metadata scraping not working properly with Fakku+

### ISSUE THREAD

**Issue by guphman** [jvlflame/FkuLibrary#2]
First of all, thank you for making this project. Very helpful for my collection.
Unfortunately, it looks like Fakku+ breaks the scraping. It's only able to properly collect the title. Probably the easiest thing to fix this would be just to give the option to only use Panda or swap to it if it detects a Fakku+ page.
Not sure if you're still interested in this project, but I thought I'd mention this just in case. Attached is an example of what happens.

[ComicInfo.zip](https://github.com/jvlflame/FkuLibrary/files/6253701/ComicInfo.zip)

**Comment by jvlflame** [comment]
Hi @guphman,

Can you provide an example link of one (or more) Fakku+ pages?  Honestly I haven't touched this project in a while but I can probably add in a simple failover in those cases.

**Comment by guphman** [comment]
https://www.fakku net/hentai/loose-yui-english
Barely any of the ones I tried from the 1-1000 actually scraped tags. Most just broke, showing the data in that zip. You can clearly see the tags aren't behind a paywall, so it may just be site changes.
Regardless, I just swapped the code and used the panda link and everything worked fine.

**Comment by jvlflame** [comment]
I updated to Fakku scraper files. Can you clone the latest from master and let me know if it works for you?

**Comment by guphman** [comment]
So I tested a group of 4 files and the ones that were found worked, however some of them weren't able to be located on either site for some reason.
![Screenshot 2021-04-04 190434](https://user-images.githubusercontent.com/81884833/113523874-c34ab780-9578-11eb-8efc-fc04ed284052.png)
I can say that they are able to be found with the previous code. I did try all the naming schemes listed in the documentation as well. None were able to be detected.

**Comment by jvlflame** [comment]
@guphman Pushed changes for files with `&` failing. Also I forgot to update the panda.chaika scraper for the updated flow, but it should work now. Can you try again?

**Comment by guphman** [comment]
![Screenshot 2021-04-04 202800](https://user-images.githubusercontent.com/81884833/113525699-6ce37600-9584-11eb-875f-27daa616a365.png)
Put some more & for testing. Some are able to be found on Fakku, others aren't. Diamond & Zirconia should be able to be detected, as I verified it still exists on Fakku.net, but the other files not detected I could not find on Fakku so those should be normal.
Still waiting to apply the new file to my entire collection, as it obviously takes some time.

**Comment by jvlflame** [comment]
Seems like the URL for  `Diamond & Zirconia - Chapter 2` doesn't match the standard fakku URL convention, which is why it's failing. My URL scraper function doesn't directly use the Fakku search to find the file, rather it creates the URL using a standard convention. I just added a new cleaning setting for files with `-` as well.

I added a two new parameters for `Set-FakkuMetadata` => `-FakkuUrl` and `-PandaChaikaUrl` which you can use to directly match files with if for some reason the matcher doesn't automatically pick it up.

```powershell
Set-FakkuMetadata -FilePath 'C:\Fakku\[Takahashi Note] City Kid & the Beast (COMIC X-Eros #46).cbz' -FakkuUrl 'https://www.fakku.net/hentai/city-kid-the-beast-english'
```

I also added a new public function called `Get-FakkuMetadata` which accepts one of two parameters `-DoujinName` or `-Url`. This can be used if you want to preview the ComicInfo.xml output. Using `-DoujinName` goes through the default flow of Fakku => panda.chaika.moe. Using `-Url` will automatically detect based on url.

```powershell
Get-FakkuMetadata -DoujinName 'Succubus Stayed Life 4'

Get-FakkuMetadata -Url 'https://panda.chaika.moe/archive/40002/'
```

Output:
```xml
<?xml version="1.0"?>
<ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Title>(C90) [NANIMOSHINAI (Sasamori Tomoe)] Succubus Stayed Life 4 [English] [SeekingEyes]</Title>
  <Series>Unknown</Series>
  <Summary></Summary>
  <Writer>Sasamori Tomoe</Writer>
  <Publisher></Publisher>
  <Genre><label class="label-extended">group:</label>, group:nanimoshinai, nanimoshinai</Genre>
  <LanguageISO>en</LanguageISO>
  <AgeRating>Adults Only 18+</AgeRating>
  <Manga>Yes</Manga>
</ComicInfo>
```

**Comment by guphman** [comment]
Wow, this all looks great. Thanks for taking the time for this. I think that's my issue resolved.

Only tangentially related, but I've been using the comicinfo files for a self hosted Komga collection, so if you're interested in making a tool for that, it looks like Komga is the best comic/manga hoster that still gets updates. Obviously not asking you to do anything, only just pointing it out in case you're interested.

**Comment by guphman** [comment]
Uh, hold on. I think something may have bugged out. Now the scraper is making every comicinfo file the same as the first one scraped.

**Comment by jvlflame** [comment]
@guphman Seems like I made a dumb logic error. I updated `Set-FakkuMetadata` to only use the parameter `-Url` instead of `-FakkuUrl` and `-PandaChaikaUrl`, so now you would call that via:

```powershell
Set-FakkuMetadata -FilePath 'C:\{doujinPath}' -Url '{$fakkuOrPandaUrl}'
```

**Comment by jvlflame** [comment]
> Only tangentially related, but I've been using the comicinfo files for a self hosted Komga collection, so if you're interested in making a tool for that, it looks like Komga is the best comic/manga hoster that still gets updates. Obviously not asking you to do anything, only just pointing it out in case you're interested.

I kind of took a break from this project after taking a delve into HappyPandaX and Lanraragi. It suited my needs better since it had metadata scraping functionality as well as a native front-end. My one issue with those solutions though is that they only save the metadata to their database, rather than locally.

I think I took a look at Komga quite a while back, but it didn't seem to have the functionality I wanted. I assume 2 years later they  are much more feature rich so I'll look again. I may end up expanding this project to include more sources if that's the case.

**Comment by guphman** [comment]
Alright, sorry I keep finding problems but here.
When trying to find the metadata for **[Chobipero] Daddy Substitute (COMIC Kairakuten 2015-09)**, the scraper skips over Fakku because it was taken down from there, but instead of pointing to https://panda.chaika.moe/archive/22179/ it points to https://panda.chaika.moe/archive/26858/
I tried to set the metadata using the manual method you added using the url, but it didn't properly write it into the zip.
The get-fakkumetadata command worked fine though.
Oh, also in the link it improperly links to, it breaks the comicinfo readability by putting <label class="label-extended">female:</label> in between the <Genre> brackets.
Also I should mention I haven't read any of the manga in the test folder, just chose them at random lol

**Comment by jvlflame** [comment]
> When trying to find the metadata for [Chobipero] Daddy Substitute (COMIC Kairakuten 2015-09), the scraper skips over Fakku because it was taken down from there, but instead of pointing to https://panda.chaika.moe/archive/22179/ it points to https://panda.chaika.moe/archive/26858/

I made some changes to the panda.chaika.moe scraper. If a search result returns multiple entries, it will now check each one and prioritize the first entry that has a publisher of `Fakku`. Otherwise if only a single result is returned, it will automatically select that one.

> I tried to set the metadata using the manual method you added using the url, but it didn't properly write it into the zip.
The get-fakkumetadata command worked fine though.

I had a bug there. If it was found on Fakku, it wouldn't use the provided -URL. (I wrote this code a long time ago so some of the logic isn't the best :D)

> Oh, also in the link it improperly links to, it breaks the comicinfo readability by putting female: in between the brackets.

I was hoping that e(x)hentai entries wouldn't show up when searching by both title and author, but it turns out they do in some instances. I added some extra logic to the panda.chaika metadata scraper to properly capture genres for them now.

> Also I should mention I haven't read any of the manga in the test folder, just chose them at random lol
Sure.. :)

Anyways, let me know if these changes fix the issues for you.

**Comment by guphman** [comment]
Sorry for the extremely late response. I've actually been testing out lanraragi for myself and similarly left this to the sideline. Everything seems to be in order, thank you for everything.
I really hope a better format than comicinfo will come along in the future so that locally hosted metadata will be more useful.

**Comment by jvlflame** [comment]
Awesome, and agreed!
